# 0 for opt mapping->wxy, 1 for loc mapping->sy.
#TODO---Done
#  slam_mode_switch: 1
#  1 for use fuse, 0 is not use
  if_use_fuseNode: 0
# 1 for debug (pub to rviz),0 for not debug
  if_debug: 1


  # the path of map save
#  you must change it to right PATH or it will crush!!!!!!!!
  save_map_path: "/home/wxy/seu/workmapping/seu_lidarloc/src/result/"
#  save_map_path: "/home/sy/SEU_WS/seu_lidarloc_new/map/"
#  save_map_path: "/home/lsy/map/"
  if_need_first_position: 0
# 1 use DR , 0 use fuse
  use_DR_or_fuse_in_loc: 1

  # Export settings
  savePCD: false                              # https://github.com/TixiaoShan/LIO-SAM/issues/3
  savePCDDirectory: "/Downloads/LOAM/"        # actually we do not use the floder to save maps

  # LOAM feature threshold
  use_deskew: true
  edgeThreshold: 1.0
  surfThreshold: 0.1
  edgeFeatureMinValidNum: 10
  surfFeatureMinValidNum: 100

  # voxel filter paprams
  DownSampleModeSwitch: 1                       # add by SY, 0 for voxel filter, 1 for uniformSample,
# 0:
  odometrySurfLeafSize: 0.4                     # default: 0.4 - outdoor, 0.2 - indoor
  mappingCornerLeafSize: 0.2                    # default: 0.2 - outdoor, 0.1 - indoor
  mappingSurfLeafSize: 0.4                      # default: 0.4 - outdoor, 0.2 - indoor
  surroundingKeyframeDensity: 2.0               # meters, downsample surrounding keyframe poses
# 1:
  odometrySurfRadiusSize_US: 0.3                     # default: 0.4 - outdoor, 0.2 - indoor
  mappingCornerRadiusSize_US: 0.2                    # default: 0.2 - outdoor, 0.1 - indoor
  mappingSurfRadiusSize_US: 0.3                      # default: 0.4 - outdoor, 0.2 - indoor
  surroundingKeyframeDensity_US: 1.0               # meters, downsample surrounding keyframe poses

  # robot motion constraint (in case you are using a 2D robot)
  z_tollerance: 1000                            # meters
  rotation_tollerance: 1000                     # radians

  # CPU Params
  numberOfCores: 8                              # number of cores for mapping optimization
  mappingProcessInterval: 0.15                  # seconds, regulate mapping frequency

  # Surrounding map
  surroundingkeyframeAddingDistThreshold: 1.0  # meters, regulate keyframe adding threshold
  surroundingkeyframeAddingAngleThreshold: 1.0  # radians, regulate keyframe adding threshold

  surroundingKeyframeSearchRadius: 50.0         # meters, within n meters scan-to-map optimization (when loop closure disabled)
  localMap_searchRadius: 30.0
  localMap_searchRadius_surf: 50.0
  localMap_searchRadius_corner: 50.0
  LocalMap_updata_perframe: 20

  if_LoadFromMapManager: 1  # 0 for load PriorMap from local, 1 for load from MapManager
  scan_2_prior_map: 1     # 0 for scan 2 localmap, 1 for scan 2 priormap, 2 for scan 2 scan
#  prior_corner_map_path: "/media/sy/R/dataSet/ZhongKeXingChi/yuanqu/global_corner.pcd"
#  prior_surf_map_path: "/media/sy/R/dataSet/ZhongKeXingChi/yuanqu/global_surf.pcd"
  prior_corner_map_path: "/home/lsy/seu_lidarloc/src/global_corner.pcd"
  prior_surf_map_path: "/home/lsy/seu_lidarloc/src/global_surf.pcd"
  scan_2_scan_num_surf: 50000
  scan_2_scan_num_corner: 30000

  # Loop closure
  loopClosureEnableFlag: true
  loopClosureFrequency: 1.0                     # Hz, regulate loop closure constraint add frequency
  surroundingKeyframeSize: 30                  # submap size (when loop closure enabled)
  historyKeyframeSearchRadius: 30.0           # meters, key frame that is within n meters from current pose will be considerd for loop closure
  historyKeyframeSearchTimeDiff: 60.0          # seconds, key frame that is n seconds older will be considered for loop closure
  historyKeyframeSearchNum: 25                  # number of hostory key frames will be fused into a submap for loop closure
  historyKeyframeFitnessScore: 0.9            # icp threshold, the smaller the better alignment

  # Visualization
  globalMapVisualizationSearchRadius: 1000.0    # meters, global map visualization radius
  globalMapVisualizationPoseDensity: 10.0       # meters, global map visualization keyframe density
  globalMapVisualizationLeafSize: 0.5           # meters, global map visualization cloud density

  # mapping
  globalMapLeafSize: 0.5                        # saved map voxgrid size



