# 0 for opt mapping->wxy, 1 for loc mapping->sy.
# TODO change yaml name
#TODO remove not used parmater!!!!
  slam_mode_switch: 1

#  if_use_

  # the path of map save
#  you must change it to right PATH or it will crush!!!!!!!!
  save_map_path: "/home/wxy/seu/reborn/11.1/seu_lidarloc/src/result/yuanqu20/"
#  save_map_path: "/media/sy/R/dataSet/ZhongKeXingChi/newbag/park_loop1_out/"
#  save_map_path: "/home/lsy/map/"
  if_need_first_position: 0
# 1 use DR , 0 use fuse
  use_DR_or_fuse_in_loc: 1

  # LOAM feature threshold
  edgeThreshold: 1.0
  surfThreshold: 0.1
  edgeFeatureMinValidNum: 10
  surfFeatureMinValidNum: 100

  # voxel filter paprams
  DownSampleModeSwitch: 1                       # add by SY, 0 for voxel filter, 1 for uniformSample,
# 0:
  odometrySurfLeafSize: 0.4                     # default: 0.4 - outdoor, 0.2 - indoor
  mappingCornerLeafSize: 0.2                    # default: 0.2 - outdoor, 0.1 - indoor
  mappingSurfLeafSize: 0.2                      # default: 0.4 - outdoor, 0.2 - indoor
  surroundingKeyframeDensity: 2.0               # meters, downsample surrounding keyframe poses
# 1:
  odometrySurfRadiusSize_US: 0.2                     # default: 0.4 - outdoor, 0.2 - indoor
  mappingCornerRadiusSize_US: 0.1                    # default: 0.2 - outdoor, 0.1 - indoor
  mappingSurfRadiusSize_US: 0.2                      # default: 0.4 - outdoor, 0.2 - indoor
  surroundingKeyframeDensity_US: 1.0               # meters, downsample surrounding keyframe poses

  # robot motion constraint (in case you are using a 2D robot)
  z_tollerance: 2                            # meters
  rotation_tollerance: 5                     # radians

  # CPU Params
  mappingProcessInterval: 0.15                  # seconds, regulate mapping frequency

  # Surrounding map
  surroundingkeyframeAddingDistThreshold: 1.0  # meters, regulate keyframe adding threshold
  surroundingkeyframeAddingAngleThreshold: 1.0  # radians, regulate keyframe adding threshold

  surroundingKeyframeSearchRadius: 50.0         # meters, within n meters scan-to-map optimization (when loop closure disabled)

  # Loop closure
  loopClosureEnableFlag: true
  loopClosureFrequency: 1.0                     # Hz, regulate loop closure constraint add frequency
  surroundingKeyframeSize: 30                  # submap size (when loop closure enabled)
  historyKeyframeSearchRadius: 30.0           # meters, key frame that is within n meters from current pose will be considerd for loop closure
  historyKeyframeSearchTimeDiff: 60.0          # seconds, key frame that is n seconds older will be considered for loop closure
  historyKeyframeSearchNum: 25                  # number of hostory key frames will be fused into a submap for loop closure
  historyKeyframeFitnessScore: 0.5           # icp threshold, the smaller the better alignment

  #LM opt
  maxIters: 20
