
#offline_mapping Setting
map_in_path: "/home/wxq/mapin"
map_out_path: "/home/wxq/mapout"
map_index_path: "home/wxq/mapin/pose_tum"
up2down_num: 4    #up_grid_size/down_grid_size，该数值必须为整数倍
lidar_range: 50
frame_sum: 184
up_grid_down: 200


