#offline_mapping Setting
#change name to map_manger.yaml
map_in_path: "/media/sy/R/dataSet/ZhongKeXingChi/newbag/park_loop1/"
map_out_path: "/media/sy/R/dataSet/ZhongKeXingChi/newbag/park_loop1_out/"
up2down_num: 2    #up_grid_size/down_grid_size，该数值必须为整数倍
lidar_range: 200 #big grid, small grid = big grid / 2
frame_sum: 1640    # frame
up_grid_size: 120
lasercloud_width: 24 # 2 x
lasercloud_height: 22 # 2 Y
lasercloud_num: 112

T_EPSILION: 0.01 #0.01 #终止条件
STEP_SIZE: 1.1 #线搜索的最大步长，理论上这个值是网格分辨率的一半，但也不能过小，当匹配效果不好时，应该放大这个参数，分辨率同理
SIZE_RESOLUTION: 5.1 #NDT网格分辨率
MAXMUN_INTERNUM: 35 #35

DOWNSIZE_LEAF: 0.3 #体素滤波size，经验判断其值因该是点云跨度最大除以30





