
# Topics
  pointCloudTopic: "/middle"               # Point cloud data
  imuTopic: "/gps_imu"                         # IMU data
  odomTopic: "odometry/imu"                   # IMU pre-preintegration odometry, same frequency as IMU
  gpsTopic: "/gps_imu"                   # GPS odometry topic from navsat, see module_navsat.launch file

# Frames
  lidarFrame: "base_link"
  baselinkFrame: "base_link"
  odometryFrame: "odom"
  mapFrame: "map"

  # GPS Settings
  useGPS: false
  updateOrigin: true                          # when you can not get a reliable gps origin points(RTK fixed)
  gpsFrequence: 10                            # set proper gps frequence to align gps and lidar timestamp
  useImuHeadingInitialization: false         # if using GPS data, set to "false"
  useGpsElevation: true                      # if GPS elevation is bad, set to "false"
  gpsCovThreshold: 8                        # m^2, threshold for using GPS data
  poseCovThreshold: 25.0                      # m^2, threshold for using GPS data
  gpsDistance: 0.5                           # the distance between two gps point used for optimization
  gtsamGNSSBetweenFactorDistance: 10        # control GNSS between factor gap, like constraint (5,5+x)

  # debug setting
  debugLidarTimestamp: false
  debugImu: false
  debugGps: true

  # lidar Settings
  sensor: velodyne                            # lidar sensor type, 'velodyne' or 'ouster' or 'livox' or 'hesai'
  N_SCAN: 80                                  # number of lidar channel (i.e., Velodyne/Ouster: 16, 32, 64, 128, Livox Horizon: 6)
  Horizon_SCAN: 1800                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048, Livox Horizon: 4000)
  downsampleRate: 1                           # default: 1. Downsample your data if too many points. i.e., 16 = 64 / 4, 16 = 16 / 1
  lidarMinRange: 1.5                          # default: 1.0, minimum lidar range to be used
  lidarMaxRange: 1000.0

  # IMU Settings
  imuAccNoise: 7.5499e-04
  imuGyrNoise: 4.304897e-04
  imuAccBiasN: 1.1416642385952368e-03
  imuGyrBiasN: 1.4428407712885209e-05
  imuGravity: 0.0
  imuRPYWeight: 0.000001

  # Extrinsics (lidar -> IMU)
#  evo: world->lidar
  imu_type: 0   # 0: 6axis, 1:9 axis
  #T_L_B
  extrinsicTrans: [ 0.0, 0.0, -0.5135 ]
  extrinsicRot: [ 0, 1, 0,
                  -1, 0, 0,
                  0, 0, 1 ]
  extrinsicRPY: [ 0, 1, 0,
                  -1, 0, 0,
                  0, 0, 1 ]

  use_gnss_deskew: false