#TODO 1111 check not used config parameters!!!!! 1111
# Topics
  pointCloudTopic: "/middle"               # Point cloud data
  imuTopic: "/gps_imu"                         # IMU data
# odomTopic: "odometry/imu"
#TODO 1111 remove not used topics
  odomTopic: "/lidar_odometry"                   # IMU pre-preintegration odometry, same frequency as IMU /lidar_odometry
  gpsTopic: "/gps_imu"                   # GPS odometry topic from navsat, see module_navsat.launch file

# Frames
#TODO 1111 remove not used frames
  lidarFrame: "base_link"
  baselinkFrame: "base_link"
  odometryFrame: "odom"
  mapFrame: "map"

  # GPS Settings
  useGPS: true
  updateOrigin: true                          # when you can not get a reliable gps origin points(RTK fixed)
  gpsFrequence: 10                            # set proper gps frequence to align gps and lidar timestamp
  useImuHeadingInitialization: false         # if using GPS data, set to "false"
  useGpsElevation: true                # if GPS elevation is bad, set to "false"
  gpsCovThreshold: 8                        # m^2, threshold for using GPS data
  poseCovThreshold: 25.0                      # m^2, threshold for using GPS data
  gpsDistance: 0.5                           # the distance between two gps point used for optimization

  # debug setting
  #TODO remove
  debugLidarTimestamp: false
  debugImu: false
  debugGps: true

  # lidar Settings
#  for RS-Ruby-80
  #
  sensor: velodyne                            # lidar sensor type, 'velodyne' or 'ouster' or 'livox' or 'hesai'
  N_SCAN: 80                                  # number of lidar channel (i.e., Velodyne/Ouster: 16, 32, 64, 128, Livox Horizon: 6)
  Horizon_SCAN: 1800                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048, Livox Horizon: 4000)
  downsampleRate: 1                           # default: 1. Downsample your data if too many points. i.e., 16 = 64 / 4, 16 = 16 / 1
  lidarMinRange: 1.5                          # default: 1.0, minimum lidar range to be used
  lidarMaxRange: 1000.0
  lidarMinRing: 5                          # default: 1.0, minimum lidar range to be used
  lidarMaxRing: 75
  gtsamGNSSBetweenFactorDistance: 5
  lidarScanDownSample: -1                      #every lidarScanDownSample times cal 1, if -1 drop
  LMOpt_Cnt: 10

  # IMU Settings
  imuAccNoise: 0.035 #VRW,加速度计随机游走。0.035m/s/√h 0.000583333
  imuGyrNoise: 0.000029089 # ARW,角度随机游走。弧度 / sqrt(hr) 0.35°/√h 0.000029089 0.006108652
  imuAccBiasN: 7.5499190771189349e-04
  imuGyrBiasN: 4.3048975399536245e-04
  imuConstBias_acc: 0.0001
  imuConstBias_gyro: 0.0001
  imuGravity: 0.0
  imuRPYWeight: 0.01
  imuHZ: 100
  imuGTSAMReset: 100
  imu_angular_v_gain: 1 # gain for gyro
  if_DR_use_Euler: 0 #use CH610 Euler in DR

# 0 for only imu mode , 1 for imu+wheel mode in ------------->DR
  if_use_Wheel_DR: 1

  # Extrinsics (lidar -> IMU)
  imu_type: 0   # 0: 6axis, 1:9 axis
  #T_L_B
  extrinsicTrans: [ 0.0, 0.0, -0.5135 ] # -0.5135
  extrinsicRot: [ 0, 1, 0,
                  -1, 0, 0,
                  0, 0, 1 ]
  extrinsicRPY: [ 0, 1, 0,
                  -1, 0, 0,
                  0, 0, 1 ]

#DR 2 lidar
  extrinsicTrans_DR: [ 0.0, 0.0, 0.5135 ] #
  extrinsicRot_DR: [ 0, -1, 0,
                  1, 0, 0,
                  0, 0, 1 ]

  use_drodom_deskew: true
  use_gnss_deskew: false
  use_unground_classify: false
